services:
  backEnd-database:
    image: mysql:8.0
    container_name: mysql-backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: backEnd-db
      MYSQL_ROOT_HOST: '%'
    volumes:
      - backEnd_db_data:/var/lib/mysql
    networks: [app-network]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

  backend:
    build: ./backEnd
    container_name: backend
    restart: always
    env_file:
      - ./backEnd/.env
    depends_on:
      backEnd-database:
        condition: service_healthy
    networks: [app-network]

  frete-service-database:
    image: mysql:8.0
    container_name: mysql-frete
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: frete-service-database
      MYSQL_ROOT_HOST: '%'
    volumes:
      - frete_service_db_data:/var/lib/mysql
    networks: [app-network]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3307:3306"

  frete-service:
    build: ./frete-service
    container_name: frete-service
    restart: always
    env_file:
      - ./frete-service/.env
    depends_on:
      frete-service-database:
        condition: service_healthy
    networks: [app-network]

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - frete-service
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    networks: [app-network]

volumes:
  backEnd_db_data:
  frete_service_db_data:

networks:
  app-network:
    driver: bridge